import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { WalletProvider } from "@/contexts/WalletContext";
import Navbar from "@/app/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WalletProvider>
          <Navbar />
          <main>
            {children}
          </main>
          <footer className="py-12 px-4 border-t border-gray-900 bg-black text-white">
            <div className="max-w-6xl mx-auto">
              <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
                <div>
                  <div className="flex items-center space-x-2 mb-4">
                    <div className="bg-gradient-to-br from-purple-500 to-cyan-500 border-2 border-cyan-400 rounded-xl w-10 h-10 flex items-center justify-center shadow-[0_0_10px_rgba(139,92,246,0.5)]">
                      <span className="text-lg font-bold text-white">A</span>
                    </div>
                    <span className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-cyan-400">
                      AshLaunch
                    </span>
                  </div>
                  <p className="text-gray-400">
                    The premier launchpad for innovative blockchain projects.
                  </p>
                </div>
                
                <div>
                  <h4 className="font-extrabold text-lg mb-4 bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-cyan-400">
                    Documentation
                  </h4>
                  <ul className="space-y-2 text-gray-400">
                    {['Docs', 'Audits', 'Terms of Service', 'Privacy Policy'].map((item, index) => (
                      <li key={index}>
                        <a href="#" className="hover:text-cyan-400 transition-colors duration-300 hover:translate-x-1 inline-block">
                          {item}
                        </a>
                      </li>
                    ))}
                  </ul>
                </div>
                
                <div>
                  <h4 className="font-extrabold text-lg mb-4 bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-cyan-400">
                    Community
                  </h4>
                  <ul className="space-y-2 text-gray-400">
                    {['Twitter', 'Discord', 'Telegram', 'Medium'].map((item, index) => (
                      <li key={index}>
                        <a href="#" className="hover:text-cyan-400 transition-colors duration-300 hover:translate-x-1 inline-block">
                          {item}
                        </a>
                      </li>
                    ))}
                  </ul>
                </div>
                
                <div>
                  <h4 className="font-extrabold text-lg mb-4 bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-cyan-400">
                    Contact
                  </h4>
                  <ul className="space-y-2 text-gray-400">
                    {['support@ashlaunch.com', 'Partnership', 'Press', 'GitHub'].map((item, index) => (
                      <li key={index}>
                        <a href="#" className="hover:text-cyan-400 transition-colors duration-300 hover:translate-x-1 inline-block">
                          {item}
                        </a>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
              
              <div className="border-t border-gray-800 mt-12 pt-8 text-center text-gray-500">
                <p>© 2024 AshLaunch. All rights reserved.</p>
              </div>
            </div>
          </footer>
        </WalletProvider>
      </body>
    </html>
  );
}